---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name:  copy WAR file to Tomcat
       copy: 
         src: '/var/snap/jenkins/4865/workspace/MavenAnsible-CICD/target/MavenAnsibleApp.war'
         dest: '/opt/tomcat/webapps/MavenAnsibleApp.war'
         remote_src: no
        
    - name: Restart Tomcat
       systemd:
        name: tomcat
        state: restarted
